### ISSUE TITLE
Make sure whole team is collaborator in github

### ISSUE THREAD

**Issue by jhampson-dbre** [hca-foundation/youngleaderscouncil#10]

**Comment by jhampson-dbre** [comment]
Please reply to this if you cannot move cards

**Comment by udaymandava** [comment]
I am not able to move the cards

**Comment by melissawheatley** [comment]
I can't move cards

**Comment by amandalynn-hs** [comment]
Not able to move cards

Also can we get Kyle Turco added?

**Comment by vinaysandela** [comment]
Added the users. Please accept the Invites. 
@amandalynn-hs  Do you have Github username for Kyle Turco?

**Comment by priyanarasimhan02** [comment]
hi

**Comment by kyleturco** [comment]
Commenting here

**Comment by vinaysandela** [comment]
Added users - @kyleturco @priyanarasimhan02 @amandalynn-hs @melissawheatley @udaymandava 

Please accept the invites. Thanks
